# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

def bump_build_number()
  latest_build_number = latest_testflight_build_number(initial_build_number: 0)
  return (latest_build_number + 1)
end

def get_version()
  version_name = lane_context[SharedValues::LATEST_TESTFLIGHT_VERSION]

  if version_name.empty?
    puts "*** Version name is empty, add version 1.0.0 ***"
    version_name = "1.0.0"
  end

  return version_name
end

platform :ios do
  desc "Release new build to TestFlight"
  lane :release_build_to_testflight do
    commit = last_git_commit
    puts "*** Starting iOS release for commit(#{commit[:abbreviated_commit_hash]}) ***"

    #read api key from app_store_connect_api_key lane variable
    api_key = lane_context[SharedValues::APP_STORE_CONNECT_API_KEY]

    #sync certificates and profiles using match
    # sync_code_signing(
    #   api_key: api_key,
    #   type: "appstore",
    #   readonly: true,
    # )

    increment_build_number(
      build_number: bump_build_number(),
      xcodeproj: "Valorant-Stats.xcodeproj"
    )
    build_app(workspace: "Valorant-Stats.xcworkspace", scheme: "Valorant-Stats")
    upload_to_testflight(api_key: api_key)
  end
end
